### ISSUE TITLE
Running the pipeline with public datasets

### ISSUE THREAD

**Issue by hacaoe** [nanoporetech/pipeline-polya-ng#2]
Hi,

I am currently trying to analyse direct RNA data from public data, where I only have access to the fastq file and none of the other files (for example the sequencing summary). Is there a potential way to still use this pipeline, when only the fastq is available?

**Comment by cjw85** [comment]
The analysis requires the primary ionic current measurement data from the sequencer in the form of fast5 files. It cannot be used with only fastq files.

**Comment by hacaoe** [comment]
Ah okay, that makes sense. Thanks or the quick answer!
